# Generated by Django 2.2 on 2020-04-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exammark',
            options={'verbose_name': 'exam_mark', 'verbose_name_plural': 'exam_marks'},
        ),
        migrations.AlterModelOptions(
            name='groupsubject',
            options={'verbose_name': 'group_subject', 'verbose_name_plural': 'group_subjects'},
        ),
    ]
